apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-node1
  namespace: postgres-operator
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: linode-block-storage-retain

---
 
apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
  namespace: postgres-operator
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: pvc-node1
  containers:
    - name: task-pv-container
      image: busybox:latest 
      volumeMounts:
        - mountPath: "/storage"
          name: task-pv-storage

