apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  namespace: postgres-operator
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path:
      "/home/sanjee/IdeaProjects/congress_api/scraper/congress"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csearch-pv-claim
  namespace: postgres-operator
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi