apiVersion: apps/v1
kind: Deployment
metadata:
  name: csearch-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csearch-api
  template:
    metadata:
      labels:
        app: csearch-api
    spec:
      containers:
        - name: csearch-api
          image: 10.0.0.3:30955/csearchapi
          ports:
            - containerPort: 3001
          env:
            - name: DB_URI
              value: "postgresql://postgres:postgres@postgres:5432/csearch"
          imagePullPolicy: Always
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name: congress-service
spec:
  type: ClusterIP
  selector:
    app: csearch-api
  ports:
    - port: 80
      targetPort: 3001

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - api.s8njee.com
      secretName: s8njee-tls
  rules:
    - host: api.s8njee.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: congress-service
                port:
                  number: 80
