apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: csearch
  replicas: 1
  template:
    metadata:
      labels:
        app: csearch
    spec:
      containers:
        - name: postgres
          image: postgres:14
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      nodeSelector:
        disktype: ssd
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim